node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/rumble-roses-xx-xbox-360-gamerip-2006 --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/rumble-roses-xx-original-soundtrack --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/champion-wrestler-arcade --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/metal-gear-solid-2-sons-of-liberty-original-soundtrack --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/metal-gear-solid-ps1-gamerip-1998 --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/rumble-roses-2004-ps2-gamerip --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/rumble-roses --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/neo-turf-masters-neo-geo-arcade --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/endorfun-1995-windows --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/death-stranding-2019 --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/death-stranding-original-score-volume-2 --playlist
node download_khinsider.js https://downloads.khinsider.com/game-soundtracks/album/death-stranding-songs-from-the-video-game-2020 --playlist